language: scala
sudo: required
dist: trusty
addons:
  apt:
    update: true

before_script:
  - git fetch --tags

jdk:
  - oraclejdk8

script:
  - curl https://raw.githubusercontent.com/scala-native/scala-native/b7851c4dc2a22c9fd9202aea3d97e2a68910b918/scripts/travis_setup.sh | bash -x
  - ./mill -i __.__.test

